### PR TITLE
Fix/commission page scroll

### PR DESCRIPTION
**Pull request by aleesteele**
- works! thank you jacque!
- didn't add to `main-menu.js` because of some conditionalities in `site-header.js`

### CODE REVIEW

**Comment by aleesteele** [comment]
Just a note on this because I couldn't figure it out myself: I sent the team @threespot an email about the issue this morning after trying a few other packages (`disable-scroll` & `body-scroll-lock`) that had the same issue. I've been playing around with it in css (opacity, etc.) as I wait on a reply. But in the meantime, switched the import

**Comment by aleesteele** [comment]
This works now!
- Implemented the package in `members.js`. Reordered the import so that it was in the proper order. Saw that prettier noted it in webpack.
- Checks if document has the `js-no-scroll` class in `site-header.js`. Instead of displaying the title (and dealing with the fact that you can still click on it when it's visible), I called `add_class_on_scroll(hiddenNavClass)` so that the bar is hidden when people open a bio. Clicking on the overlay or the `x` icon exits as well.

**Comment by jnschrag** [comment]
> There was an additional issue If the page is scrolling down, the page defaulted to not showing the menu. If it's scrolling up, the page defaults to showing the nav bar. It mimics the display properties of the scroll behavior, so for now, I defaulted to calling add_class_on_scroll(hiddenNavClass) so that the bar is hidden when people open a bio. Do you have a preference? I can look up whether it's possible to disable clicking on the menu, and have it default to display?

I think my preference would be to have the menu visible and clickable, so the user can choose to navigate away from the page if they want to.

**Comment by aleesteele** [comment]
In that case - the header displays by default. Changed the z-index of the modal so that the menu in desktop & mobile display at the same time.

**Comment by jnschrag** [comment]
screen shot 2018-10-30 at 9 43 50 am

Can you take another look at the z-indexing on the overlay? The  modal needs to be above it. :)

**Comment by aleesteele** [comment]
Fixed! Lesson learned, clear the cache before pushing!!

**Pull request merged**
